### PR TITLE
(feat): Implement conn.reset() - fixes #1

### LINKED ISSUE #1: Implement connection.reset(options)
Clears status & cache, aborts all pending requests.
`options` as the same as in [Constructor](#Constructor)

Example

```js
connection.reset(options).then(function () {
  connection.ok === undefined // true
})
```

See [README](https://github.com/hoodiehq/hoodie-client-connection/blob/master/README.md#connectionreset-function----promise)

### PR DESCRIPTION
**Pull request by nolanlawson**
This only implements reset() itself, without support
for options. Supporting options are a TODO.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Lemme know if I got something wrong here; I was kinda unsure about how to simulate the localStorage state or the current time.

**Comment by gr2m** [comment]
merged via aab4fdc :+1: 

I've rephrased your commit message, `(feat): ...` should be `feat: ...` and optionally `feat(scope): ...`

**Comment by nolanlawson** [comment]
Thanks, I should have looked more carefully at the commit message format... -_-

**Comment by gr2m** [comment]
naaaah, plaese don't worry about it :) Thanks for the great PR

**Pull request closed without merging**
