### PR TITLE
connectionStatus.reset aborts pending request

### LINKED ISSUE #21: connectionStatus.reset should abort pending request
`nets` returns an object with a an `abort` method.

```js
var request = nets('http://example.com')
request.abort()
```

If a request error is caused by an abort, the state should not be changed, it should be ignored.

---

- [x] claim this issue (@nathanstilwell)
- [x] start a pull request (https://github.com/hoodiehq/hoodie-client-connection-status/pull/25)
- [x] write tests
- [x] implement
- [x] update README
- [ ] review & merge

Ping me in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/gr2m/) if you have any questions

### PR DESCRIPTION
**Pull request by nathanstilwell**
This is work in progress. The commits will be rebased with appropriate commit messages and documentation later.

closes #21

### CODE REVIEW

**Comment by gr2m** [comment]
@nathanstilwell I know why you got stuck now, it’s complicated :tm: I'll fix it up and we can discuss changes then

**Comment by gr2m** [comment]
The problem was that we used a promise in `check.js` that we could not mock. We could mock the `nets` call, but then the `reject()` / `resolve()` calls wouldn’t happen in its callback, and the Promise returned by `.check()` would remain pending.

So what I did is to move the `nets` call into a utils module, so we could mock it entirely. And then add some magic to add the `.abort` method to the promise. So `state.request` is now the promise returned by our `lib/utils/request.js`, and we set `promise.abort` in there.

Does that all make sense?

**Comment by gr2m** [comment]
I finished this up, hope you don’t mind @nathanstilwell. We got more starter issues if you’d like contribute again :)
http://go.hood.ie/hoodie-starter-issues

**Comment by nathanstilwell** [comment]
Hey @gr2m. Not worries. Life got in the way and I _timed out_ on this issue. Once things settle, I'm looking forward to digging back in to contributing.

**Comment by gr2m** [comment]
Looking forward to hear back from you, whenever you feel like it :)

**Pull request merged**
