### PR TITLE
Cover all the things (with tests)

### LINKED ISSUE #4: Bring code coverage to 100%
current status: [Coverage Status](https://coveralls.io/r/hoodiehq/hoodie-client-connection-status?branch=master)

```
npm run test:coverage

...

=============================== Coverage summary ===============================
Statements   : 98.15% ( 106/108 )
Branches     : 97.83% ( 45/46 )
Functions    : 93.33% ( 14/15 )
Lines        : 98.15% ( 106/108 )
================================================================================
```

---

- [x] claim this issue (@janecakemaster)
- [x] start a pull request
- [ ] write tests untit 100% coverage is reached
- [ ] review & merge

Ping me in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/gr2m/) if you have _any_ questions.

### PR DESCRIPTION
**Pull request by janecakemaster**
this PR brings coverage from 98% to 100% by writing extra unit tests for
* request
* on/off
* check
* startChecking
* reset

close #4

### CODE REVIEW

**Comment by janecakemaster** [comment]
@gr2m are there any notes anywherea bout how to format the PR message for travis?

**Comment by janecakemaster** [comment]
@gr2m the lines lacking coverage are all related to aborting the promise when a request exists. i've been trying to wrap my head around how to get into that state where a request has already been made for a test, but idk how to do that. any thoughts?

**Comment by gr2m** [comment]
Great work so far @janecakemaster :+1: 

The best way to test methods in certain states are unit tests. For example, you could create a new unit test for the reset() method, where you create your own state just as you want it, e.g. like this:

```js
var state = {
  method: 'HEAD',
  url: 'https://example.com/ping',
  cache: {},
  emitter: {
    emit: simple.stub()
  },
  request: {
    abort: simple.stub()
  }
}
```

and then pass that in directly

```js
var reset = require('../../lib/reset')
reset(state)
```

That way you only test what is happening in this one method, everything else can be mocked.

You can give a try yourself. If you get stuck, here is how the `tests/unit/reset.js` file could look like: https://gist.github.com/3d1dda25434762103a85 – make sure to add it to `tests/unit/index.js`

Does that help?

**Comment by janecakemaster** [comment]
That part is clear to me, but what's not clear to me is how to make sure that `promise.abort` in the request module gets tested. so far there is no way to actually fake a request currently in progress

screen shot 2016-01-24 at 11 52 30

**Comment by gr2m** [comment]
looking into it

**Comment by gr2m** [comment]
@janecakemaster okay, so to test the abort method, we need to add an integration test, that sends a request and right away calls `.reset()` so that the request gets aborted before the response arrives. 

This test should do, you can add it to `test/integration/reset.js`

```js
test('connection.reset() aborts requests', function (t) {
  t.plan(4)

  var connectionStatus = new ConnectionStatus({
    url: 'https://abort-example.com/ping'
  })

  connectionStatus.check()

  .catch(function (error) {
    t.is(error.name, 'AbortError', '.check() rejects with AbortError')
    t.is(error.message, 'Aborted', '.check() rejects with message "Aborted"')
    t.is(error.code, 0, '.check() rejects with error 0')
  })

  connectionStatus.reset().then(function () {
    t.pass('reset resolves')
  })
})
```

Does that make sense? Please ask away if you have any questions. I remember myself being very confused about unit vs. integration tests et all

**Comment by janecakemaster** [comment]
thanks for the offline explanation @gr2m! 
```
=============================== Coverage summary ===============================
Statements   : 100% ( 154/154 )
Branches     : 93.75% ( 45/48 )
Functions    : 100% ( 27/27 )
Lines        : 100% ( 154/154 )
===============================================================================
```

ready after your OK!

**Comment by gr2m** [comment]
It looks great :+1: we need to squash the commits. For `lib/check.js`, commit it as `chore: typo`, the rest we can commit as `test: 100% coverage`. Do you want to do it? Let me know if you need any help

**Comment by janecakemaster** [comment]
squashed nd ready to go

**Comment by gr2m** [comment]
https://media.giphy.com/media/zLoryjshXsQBa/giphy.gif

**Comment by Charlotteis** [comment]
:tada:

**Comment by nickcolley** [comment]
:100: :+1: :cake: :tada:

**Pull request merged**
